name: piece_enchanter
piecehammer: Hammer
m_name: $mod_epicloot_assets_enchanter
sizeMultiplier: 1
m_description: >
  $mod_epicloot_assets_enchanter_introduce
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: $piece_workbench
piecehammerCategory: BuildingStonecutter
minStationLevel: 1
amount: 1
disabled: true
adminonly: false
comfort: 
groundPiece: false
ground: false
waterPiece: false
noInWater: true
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
notOnWood: false
wearNTearData: 
craftingStationData: 
cSExtensionData: 
contData: 
smelterData: 
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
incineratorData: 
fireplaceData: 
teleportWorldData: 
build:
- Stone:10:1:True
- SurtlingCore:3:1:True
- Copper:3:1:True
