unique_name: ghost_kill
display_name: Ghastly
sprite_name: YagluthDrop
description: Mata <color=orange>10</color> fantasmas del bosque negro
lore: Practically impossible to find any damn ghosts.
start_message: ''
stop_message: ''
tooltip: ''
defeat_key: defeated_ghost
achievement_type: CustomKills
custom_group_key: ''
custom_pickable_name: ''
goal: 10
duration: 0
reward_type: StatusEffect
achievement_group: ''
achievement_index: 0
item: ''
item_amount: 0
skill: ''
skill_amount: 0
class_experience: 0
start_effects:
- sfx_coins_placed
stop_effects: []
damage_modifiers:
- m_type: Blunt
  m_modifier: Normal
- m_type: Slash
  m_modifier: Normal
- m_type: Pierce
  m_modifier: Normal
- m_type: Chop
  m_modifier: Normal
- m_type: Pickaxe
  m_modifier: Normal
- m_type: Fire
  m_modifier: Normal
- m_type: Frost
  m_modifier: Normal
- m_type: Lightning
  m_modifier: Normal
- m_type: Poison
  m_modifier: Normal
- m_type: Spirit
  m_modifier: Normal
modifiers:
  Attack: 1
  HealthRegen: 1
  StaminaRegen: 1
  RaiseSkills: 1
  Speed: 1.05
  Noise: 0.5
  MaxCarryWeight: 0
  Stealth: 0
  RunStaminaDrain: 0.25
  DamageReduction: 0.15
  FallDamage: 0.5
  EitrRegen: 1
